### ISSUE TITLE
UI Scaling Based on Window Size

### ISSUE THREAD

**Issue by Mebiius** [Basiiii/Profit-Taker-Analytics#36]
**Is your feature request related to a problem? Please describe.**
When you align the window vertically, the fourth phase section doesn't get to be displayed, you always have to scroll for it. 

**Describe the solution you'd like**
Consider making the UI elements smaller or scaled based on the current window size. 

**Describe alternatives you've considered**
egg

**Additional context**
![image](https://github.com/Basiiii/Profit-Taker-Analytics/assets/96760639/3b175f68-df74-4430-a795-6e9a92a4eec4)

**Comment by Basiiii** [comment]
@Mebiius Thank you for the report! The feature has been implemented and will be available in version **0.6.0** of the app. 🚀
