### ISSUE TITLE
"Best" time displays per category with diff

### ISSUE THREAD

**Issue by Reava** [Basiiii/Profit-Taker-Analytics#47]
Hey there,

Feature adds a "best" category in your global stats, per category. 
The same as the average times per category, but display the lowest time we've ever gotten on each category.

It could be a full display of all time best, or even a +- diff between last/avg run displays to best, the same way speedrun segmentation tools show diff to pb.
(or maybe even last... although idk why someone would want that lol)
Ideally, these could be switched between each in settings. 

Additionally could be segmented per spawn location as per last feature request, there are many ways to go about this. (aka best flight time on shroom spawn seperated from lake spawn)

Thank you, hopefully i was as clear as possible, examples below

**Last run screen showing Average time per category + diff:**
![LastRunShowingAVGWithDiff](https://github.com/Basiiii/Profit-Taker-Analytics/assets/93742413/e3e54b00-e231-48c8-8a21-3aea8942204f)

**Average stats screen showing Best times and diff per category**
![AverageShowingBestAndDiff](https://github.com/Basiiii/Profit-Taker-Analytics/assets/93742413/fc1586ec-cfc5-44ca-93fa-69a63bccc058)

**Last run screen showing Best time per category + diff:**
![LastRunShowingBestWithDiff](https://github.com/Basiiii/Profit-Taker-Analytics/assets/93742413/7f14d141-bf5e-4814-ae85-8d3a15bcfdce)

This would allow quick view and review of areas where people arent really reliable on/have the most they could improve on on a perfect run.

**Comment by Reava** [comment]
Just in case for the examples i posted that i didn't adjust any padding and while it bothers me i didn't want to change anything else than what im suggesting to add.

**Comment by Basiiii** [comment]
@Reava Thank you for the feature request, it's on the list to be implemented by version 1.0.0

**Comment by Basiiii** [comment]
**Partially implemented for v0.9.1.

Added difference vs best run in last run screen, others have not been implemented yet.**

**Comment by Basiiii** [comment]
Since the functionality that has not been implemented is available on another page, I am closing this issue. I do not think replicating functionality across pages is enough of a benefit.

If you wish for the remaining functionality to be added to the main page then please open another issue.
