### ISSUE TITLE
Share feature on analytics screen

### ISSUE THREAD

**Issue by Reava** [Basiiii/Profit-Taker-Analytics#48]
**Is your feature request related to a problem? Please describe.**
We can share the last run screen, but not the analytics screen.

**Describe the solution you'd like**
Port the feature from the home tab to the analytics tab too

**Describe alternatives you've considered**
Porting the feature :))

**Additional context**
Graph is cool

**Comment by Basiiii** [comment]
Functionality has been fully implemented and will be available in the next release.
