### ISSUE TITLE
Total Phase Time in Home Screen

### ISSUE THREAD

**Issue by KalaayPT** [Basiiii/Profit-Taker-Analytics#52]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to view the phase times on the home page of the app.

**Describe the solution you'd like**
so as of right now, the run screen shows timestamps of when a phase is over, from what i understand. i would also like an implementation of just the total phase time, i.e. how long that phase on its own took (basically just "this phase" minus "phase before it"). ive seen the method reava suggested for average times and how theyre displayed and maybe this could be implemented in the same way. maybe even move the "phase over" timestamp thats there currently somewhere else, maybe in the bottom right corner or something like "first phase - [timestamp]" in the phase title

**Describe alternatives you've considered**

**Additional context**

**Comment by Basiiii** [comment]
@KalaayPT Thank you for your feedback, this will be added to the list of features to be implemented by the next version of the app.
