### ISSUE TITLE
Best and last run diff should compare the last PB if last run is PB

### ISSUE THREAD

**Issue by Neppkun** [Basiiii/Profit-Taker-Analytics#55]
**Is your feature request related to a problem? Please describe.**
It is not.

**Describe the solution you'd like**
When you get a PB, the "best run" difference in the main menu shows the PB run, making the difference "-0.00" (see image). ![i](https://owo.whats-th.is/3Y1DRJX.png)
While this is a valid indicator you got PB, it also doesn't let you see how much you improved.
So, if you got PB in your last run, the difference should be between the PB you just got, and your last PB run.
There could also be a text after the run name to indicate it's a PB.

**Describe alternatives you've considered**
If this sounds like it'll be confusing, then hovering over the Total Duration could show your last PB run instead of changing the difference.

**Comment by Basiiii** [comment]
Thank you for creating the issue, this is a valid point and I'll try to get it implemented by the next version release of the app!
