### ISSUE TITLE
Runs don't like to be deleted

### ISSUE THREAD

**Issue by Neppkun** [Basiiii/Profit-Taker-Analytics#58]
**Describe the bug**
When you delete runs, they get deleted, and removed from the file storage. But when you restart the app, they magically appear again.
I tried to clear the temp folder, thinking that might be the issue, even still, they don't like to be deleted.

**To Reproduce**
- open the app
- delete a run (or multiple)
- restart the app
Deleted runs will return

**Expected behavior**
Deleted runs should stay deleted, and not return to the file storage on restart.

**Screenshots**
Here's a video of me re-producing the bug: https://owo.whats-th.is/4ubuwJZ.mp4

**Comment by Basiiii** [comment]
@Neppkun Thank you for the report.

I believe this isn't a bug and it could be that the parser is getting all your runs that you recently completed. Are those runs that are appearing runs you did the last time you played the game?

Could you please try deleting the runs, then deleting the ``EE.log`` file located at ``%localappdata%/Warframe/EE.log``, full location can look something like: ``C:\Users\user\AppData\Local\Warframe\EE.log``.

This EE.log file is generated by Warframe (as you may know) and contains information on your past runs, it's very possible the app is getting those runs.


So please, test using the following steps:

- Open the app
- Delete runs using app and check if files get deleted
- Delete the EE.log file
- Close the app
- Open the app again and see if runs appear


Please write back here with the results, you can attach files here too.
Thank you!

**Comment by Neppkun** [comment]
@Basiiii Yep, you were right.
Deleting the EE.log fixed this issue.

Though, just to add, deleting the log file while the program is open isn't possible (at least not within the Explorer GUI) as the file is being read from by the parser. So I had to delete the runs, close the parser first, then delete the log file.

I think it would be a nice idea to make it so when you delete runs, the EE.log is also deleted. (And warn the user that it will be deleted, as it may result in some unwanted behavior. Would maybe also need to kill the parser.exe process before doing it but I'm not sure if Windows will complain about that since it's not being done through Explorer)
